<template>
  <div class='helpDocument layout'>
    <Layout>
      <Sider hide-trigger width='300px'>
        <Menu @on-select='menuChange'  width='300px' active-name="1-1" :open-names="['1','2','3']">
          <Submenu  v-for='(v,i) in list' :key='v+i' :name="v.name">
            <template slot="title">{{v.title}}</template>
              <template  v-for='(value,index) in v.children' >
                <template v-if='value.isParent'>
                  <Submenu :name="value.name">
                    <template slot="title">{{value.title}}</template>
                    <template v-for='(val,ind) in value.children'>
                      <MenuGroup v-if='val.children&&val.children.length'  :key='val+ind' :title="val.title">
                        <MenuItem v-for='(item,itemIndex) in val.children' :key='item+itemIndex' :name="item.name">{{item.title}}</MenuItem>
                      </MenuGroup>
                      <MenuItem  :key='val+ind' v-if='!val.children||!val.children.length' :name="val.name">{{val.title}}</MenuItem>
                    </template>
                </Submenu>
                </template>
                <template v-else>
                  <MenuGroup v-if='value.children&&value.children.length'  :key='value+index' :title="value.title">
                    <MenuItem v-for='(item,itemIndex) in value.children' :key='item+itemIndex' :name="item.name">{{item.title}}</MenuItem>
                  </MenuGroup>
                  <MenuItem  :key='value+index' v-if='!value.children||!value.children.length' :name="value.name">{{value.title}}</MenuItem>
                </template>
              </template>
          </Submenu>
        </Menu>
      </Sider>
      <Layout class='centerContent'>
        <center-content
          :list='contentData'
        ></center-content>
      </Layout>
    </Layout>
  </div>
</template>

<script>
import centerContent from './content';
import store from '@/store'
console.dir(store.state.user)
const fourData = {
          headTitle:'商户入驻“四步曲”',
          children:[
            {
              title:'一、注册/登录',
              children:[
                {
                  title:'1.注册',
                  describe:'根据提示，填写相关信息完成注册，等待审核',
                  img:require('../../../assets/images/helpImg/01/1.1.png'),
                  id:'1-1-1',
                },
                {
                  title:'2.登录',
                  describe:'收到注册成功通知，可使用注册手机号或登录名进行登录；',
                  img:require('../../../assets/images/helpImg/01/1.2.png'),
                  id:'1-1-2',
                }
              ]
            },
            {
              title:'二、新增售卖商品',
              children:[
                {
                  title:'1.新增商品类型',
                  describe:'新增商品类型，用于：自助售卖机分类展示；',
                  img:require('../../../assets/images/helpImg/01/2.1.png'),
                  id:'1-3-1',
                },
                {
                  title:'2.新增商品',
                  describe:'在“商品中心”中加入需要售卖的商品（可直接在商品库中新增，也可以自定义新增）；',
                  img:require('../../../assets/images/helpImg/01/2.2.png'),
                  id:'1-3-2',
                },
                {
                  title:'3.新增价格模板（选择性）',
                  describe:'新增价格模板，可用于和点位关联（用于特殊点位价格特殊的情况）；',
                  img:require('../../../assets/images/helpImg/01/2.3.png'),
                  id:'1-3-3',
                }
              ]
            },
            {
              title:'三、管理设备',
              children:[
                {
                  title:'1.新增分区线路',
                  describe:'新增“分区”及“线路”（用于将设备分区管理，分区下面可新增分区或线路，线路不可再新增，用于直接关联设备）；',
                  img:require('../../../assets/images/helpImg/01/3.1.png'),
                  id:'1-4-1',
                },
                {
                  title:'2.新增点位',
                  describe:'新增点位，和线路关联，可选择性绑定设备、价格模板；',
                  img:require('../../../assets/images/helpImg/01/3.2.png'),
                  id:'1-4-2',
                },
                {
                  title:'3.新增货道商品模板（选择性）',
                  describe:'新增货道商品模板，后续为设备上架售卖商品提供模板；',
                  img:require('../../../assets/images/helpImg/01/3.3.png'),
                  id:'1-4-3',
                },
                {
                  title:'4.新增利益分配模板（选择性）',
                  describe:'新增收款方及其账户，再根据每个设备的利益分配设置对应的利益分配模板；',
                  img:require('../../../assets/images/helpImg/01/3.4.png'),
                  id:'1-4-4',
                },
                {
                  title:'5.设定设备各项信息并“启用”',
                  id:'1-4-5',
                  children:[
                    {
                      describe:'5.1为设备绑定点位；',
                      img:require('../../../assets/images/helpImg/01/3.5.1.png'),
                    },
                    {
                      describe:'5.2货道商品中，如对货道有特殊要求，可点击“复位货道”，根据自身需求设定货道，并可选择性上架商品或后续使用商户APP”云自购“完成上架；',
                      img:require('../../../assets/images/helpImg/01/3.5.2.png'),
                    },
                    {
                      describe:'5.3为设备绑定利益模板（若不绑定，则全部默认为商户收款）；',
                      img:require('../../../assets/images/helpImg/01/3.5.3.png'),
                    },
                    {
                      describe:'5.4完成上述操作后，点击“启用”，即可正式开始运营；',
                      img:require('../../../assets/images/helpImg/01/3.5.4.png'),
                    }
                  ]
                }
              ]
            },
            {
              title:'四、用户分配',
              children:[
                {
                  title:'1.新增角色',
                  describe:'可根据自身运营情况，新增角色，并分配对应的权限；',
                  img:require('../../../assets/images/helpImg/01/4.1.png'),
                  id:'1-5-1',
                },
                {
                  title:'2.新增用户',
                  describe:'新增子用户，可根据需求为每个用户设置对应的角色、管理分区、以及开门权限；',
                  img:require('../../../assets/images/helpImg/01/4.2.png'),
                  id:'1-5-2',
                }
              ]
            },
          ],
        };
const fiveData = {
          headTitle:'商户入驻“五步曲”',
          children:[
            {
              title:'一、注册/登录',
              children:[
                {
                  title:'1.注册',
                  describe:'根据提示，填写相关信息完成注册，等待审核',
                  img:require('../../../assets/images/helpImg/01/1.1.png'),
                  id:'1-1-1',
                },
                {
                  title:'2.登录',
                  describe:'收到注册成功通知，可使用注册手机号或登录名进行登录；',
                  img:require('../../../assets/images/helpImg/01/1.2.png'),
                  id:'1-1-2',
                }
              ]
            },
            {
              title:'二、商户收款码配置',
              children:[
                {
                  title:' ',
                  describe:'根据提示，完成收款码配置，待审核通过即可；',
                  img:require('../../../assets/images/helpImg/01/shoukuanma.png'),
                  id:'1-2',
                }
              ]
            },
            {
              title:'三、新增售卖商品',
              children:[
                {
                  title:'1.新增商品类型',
                  describe:'新增商品类型，用于：自助售卖机分类展示；',
                  img:require('../../../assets/images/helpImg/01/2.1.png'),
                  id:'1-3-1',
                },
                {
                  title:'2.新增商品',
                  describe:'在“商品中心”中加入需要售卖的商品（可直接在商品库中新增，也可以自定义新增）；',
                  img:require('../../../assets/images/helpImg/01/2.2.png'),
                  id:'1-3-2',
                },
                {
                  title:'3.新增价格模板（选择性）',
                  describe:'新增价格模板，可用于和点位关联（用于特殊点位价格特殊的情况）；',
                  img:require('../../../assets/images/helpImg/01/2.3.png'),
                  id:'1-3-3',
                }
              ]
            },
            {
              title:'四、管理设备',
              children:[
                {
                  title:'1.新增分区线路',
                  describe:'新增“分区”及“线路”（用于将设备分区管理，分区下面可新增分区或线路，线路不可再新增，用于直接关联设备）；',
                  img:require('../../../assets/images/helpImg/01/3.1.png'),
                  id:'1-4-1',
                },
                {
                  title:'2.新增点位',
                  describe:'新增点位，和线路关联，可选择性绑定设备、价格模板；',
                  img:require('../../../assets/images/helpImg/01/3.2.png'),
                  id:'1-4-2',
                },
                {
                  title:'3.新增货道商品模板（选择性）',
                  describe:'新增货道商品模板，后续为设备上架售卖商品提供模板；',
                  img:require('../../../assets/images/helpImg/01/3.3.png'),
                  id:'1-4-3',
                },
                {
                  title:'4.新增利益分配模板（选择性）',
                  describe:'新增收款方及其账户，再根据每个设备的利益分配设置对应的利益分配模板；',
                  img:require('../../../assets/images/helpImg/01/3.4.png'),
                  id:'1-4-4',
                },
                {
                  title:'5.设定设备各项信息并“启用”',
                  id:'1-4-5',
                  children:[
                    {
                      describe:'5.1为设备绑定点位；',
                      img:require('../../../assets/images/helpImg/01/3.5.1.png'),
                    },
                    {
                      describe:'5.2货道商品中，如对货道有特殊要求，可点击“复位货道”，根据自身需求设定货道，并可选择性上架商品或后续使用商户APP”云自购“完成上架；',
                      img:require('../../../assets/images/helpImg/01/3.5.2.png'),
                    },
                    {
                      describe:'5.3为设备绑定利益模板（若不绑定，则全部默认为商户收款）；',
                      img:require('../../../assets/images/helpImg/01/3.5.3.png'),
                    },
                    {
                      describe:'5.4完成上述操作后，点击“启用”，即可正式开始运营；',
                      img:require('../../../assets/images/helpImg/01/3.5.4.png'),
                    }
                  ]
                }
              ]
            },
            {
              title:'五、用户分配',
              children:[
                {
                  title:'1.新增角色',
                  describe:'可根据自身运营情况，新增角色，并分配对应的权限；',
                  img:require('../../../assets/images/helpImg/01/4.1.png'),
                  id:'1-5-1',
                },
                {
                  title:'2.新增用户',
                  describe:'新增子用户，可根据需求为每个用户设置对应的角色、管理分区、以及开门权限；',
                  img:require('../../../assets/images/helpImg/01/4.2.png'),
                  id:'1-5-2',
                }
              ]
            },
          ],
        };
const nineData = {
  title:'九、平台管理',
  children:[
    {
      title:'1.商户管理',
      children:[
        {
          describe:'1.1商户信息管理（对所有的商户进行管理，审核各类信息，分配经营范围、收款权限、利润抽成比、活动权限）；',
          img:require('../../../assets/images/helpImg/02_2/9.1.1.png'),
          id:'2-9-1-1',
        },
        {
          describe:'1.2商户收钱码管理(审核/查看商户收钱码配置信息）',
          img:require('../../../assets/images/helpImg/02_2/9.1.2.png'),
          id:'2-9-1-2',
        }
      ]
    },
    {
      title:'2.商品管理',
      describe:'建立商品分类，并逐一添加商品填充商品库以供商户售卖，同时对商户自身新增的商品进行审核；',
      img:require('../../../assets/images/helpImg/02_2/9.2.png'),
      id:'2-9-2',
    },
    {
      title:'3.设备管理',
      children:[
        {
          describe:'3.1设备列表（ 批量上传模板、批量导入、设备转移、使用期限、维护费用、货道模板、开门记录、出厂信息、设备类型）；',
          img:require('../../../assets/images/helpImg/02_2/9.3.1.png'),
          id:'2-9-3-1',
        },
        {
          describe:'3.2设备模板',
          img:require('../../../assets/images/helpImg/02_2/9.3.2.png'),
          id:'2-9-3-2',
        }
      ]
    }
  ]
}
let contentData = [
        {
          headTitle:'详细教程及功能概览',
          children:[
            {
              title:'一、首页',
              children:[
                {
                  title:'',
                  describe:'',
                  img:require('../../../assets/images/helpImg/02_1/1.png'),
                  id:'2-1',
                },
                {
                  title:'1.导航栏',
                  describe:'收起/展开菜单、进入/退出全屏、密码修改、更换logo、退出登录、查看帮助文档；',
                  img:require('../../../assets/images/helpImg/02_1/1.1.png'),
                },
                {
                  title:'2.活动菜单',
                  describe:'切换、关闭所有、关闭其他；',
                  img:require('../../../assets/images/helpImg/02_1/1.2.png'),
                },
                {
                  title:'3.信息展示',
                  describe:'展示今日销售额/昨日销售额、今日利润/昨日利润、设备数（各类型设备数）、销售额（近七天/近三十天/近半年）各类统计信息；',
                }
              ]
            },
            {
              title:'二、商户（商户信息）',
              children:[
                {
                  describe:'设置商户收款码、新增子商户、编辑自身商户信息；',
                  img:require('../../../assets/images/helpImg/02_1/2_youshoukuanma.png'),
                  id:'2-2',
                }
              ]
            },
            {
              title:'三、商品',
              children:[
                {
                  title:'1.商品类型',
                  describe:'编辑/查看/新增商品类型，用于A端售卖机分类售卖；',
                  img:require('../../../assets/images/helpImg/02_1/3.1.png'),
                  id:'2-3-1',
                },
                {
                  title:'2.商品中心',
                  describe:'展示自身商户及子商户所有商品.，可新增商品（新增商品库商品、自定义商品），自定义商品需通过审核才可上架售卖；可查看进价历史修改信息，商品可上架、下架、编辑、删除（已绑定模板商品不可删除）；',
                  img:require('../../../assets/images/helpImg/02_1/3.2.png'),
                  id:'2-3-2',
                },
                {
                  title:'3.商品价格模板',
                  describe:'新增商品价格模板（用于和设备点位关联，每个点位有不同的价格模板，选择性新增）',
                  img:require('../../../assets/images/helpImg/02_1/3.3.png'),
                  id:'2-3-3',
                },
              ]
            },
            {
              title:'四、设备',
              children:[
                {
                  title:'1.设备管理',
                  id:'2-4-1',
                  children:[
                    {
                      img:require('../../../assets/images/helpImg/02_1/4.1.png'),
                    },
                    {
                      describe:'1.1.新增自营设备',
                      img:require('../../../assets/images/helpImg/02_1/4.1.1.png'),
                    },
                    {
                      describe:'1.2.设定点位',
                      img:require('../../../assets/images/helpImg/02_1/4.1.2.png'),
                    },
                    {
                      describe:'1.3.货道商品(可设定改设备货道以及货道内售卖的商品，也可直接在商户APP中直接上架)',
                      img:require('../../../assets/images/helpImg/02_1/4.1.3.png'),
                    },
                    {
                      describe:'1.4.设定利益分配（需先设定点位才可以设定利益分配）',
                      img:require('../../../assets/images/helpImg/02_1/4.1.4.png'),
                    }
                  ]
                },
                {
                  title:'2.分区线路设置',
                  describe:'新增分区或线路（分区下面可继续新增分区以及线路，线路下面不可新增，用于直接关联点位）',
                  img:require('../../../assets/images/helpImg/02_1/4.2.png'),
                  id:'2-4-2',
                },
                {
                  title:'3.点位管理',
                  img:require('../../../assets/images/helpImg/02_1/4.3.png'),
                  id:'2-4-3',
                },
                {
                  title:'4.货道商品模板设置',
                  describe:'新增分区或线路（分区下面可继续新增分区以及线路，线路下面不可新增，用于直接关联点位）',
                  img:require('../../../assets/images/helpImg/02_1/4.4.png'),
                  id:'2-4-4',
                },
                {
                  title:'3.点位管理',
                  img:require('../../../assets/images/helpImg/02_1/4.5.png'),
                  id:'2-4-5',
                },
                {
                  title:'6.GIS',
                  describe:'在地图上展示所有设备（自身以及子商户），每个类型的设备做了颜色区分；',
                  img:require('../../../assets/images/helpImg/02_1/4.6.png'),
                  id:'2-4-6',
                },
              ]
            },
            {
              title:'五、库存',
              children:[
                {
                  title:'1.库存监控',
                  describe:'展示所有设备内的商品总和以及每个设备内各商品数量；',
                  img:require('../../../assets/images/helpImg/02_1/5.1.png'),
                  id:'2-5-1',
                },
                {
                  title:'2.补货记录',
                  describe:'记录每次补货的信息；',
                  id:'2-5-2',
                }
              ]
            },
            {
              title:'六、促销活动',
              children:[
                {
                  title:'促销活动（活动列表）',
                  describe:'展示商户自身以及子商户的活动，活动分为“低价促销”及“限免”两个类型，其中“限免”活动仅限环保购物袋；活动分为：活动中、待开始、已结束以及启用和停用状态；活动中不能修改只能删除，待开始则可以根据需求修改；',
                  img:require('../../../assets/images/helpImg/02_1/6.png'),
                  id:'2-6',
                }
              ]
            },
            {
              title:'七、销售结算',
              children:[
                {
                  title:'1.交易列表',
                  describe:'展示商户自身以及子商户的交易订单，可点击查看订单的“点位信息”、“订单详情”、“利益分配”，每个订单均有退款功能，出货失败的订单有清算功能。（退款与清算功能只能选其一）',
                  img:require('../../../assets/images/helpImg/02_1/7.1.png'),
                  id:'2-7-1',
                },
                {
                  title:'2.结算列表',
                  describe:'展示商户自身以及子商户的结算列表，从收款方入手展示每笔资金来源，可查看关联设备、收款人详情、结算详情（可导出），在有收款权限的情况下有结算功能；',
                  img:require('../../../assets/images/helpImg/02_1/7.2.png'),
                  id:'2-7-2',
                },
                {
                  title:'3.结算记录',
                  describe:'展示商户自身以及子商户的已结算记录，从收款方入手展示每笔资金来源，可查看关联设备、收款人详情、结算详情（可导出）；',
                  img:require('../../../assets/images/helpImg/02_1/7.3.png'),
                  id:'2-7-3',
                }
              ]
            },
            {
              title:'八、系统',
              children:[
                {
                  title:'1.用户管理',
                  describe:'部门管理、用户新增、开门权限、管理分区、角色等；',
                  img:require('../../../assets/images/helpImg/02_1/8.1.png'),
                  id:'2-8-1',
                },
                {
                  title:'2.角色管理',
                  describe:'新建角色，并为每个角色分配每个页面的权限；',
                  img:require('../../../assets/images/helpImg/02_1/8.2.png'),
                  id:'2-8-2',
                }
              ]
            },
          ]
        }
      ];
const four = {
          title:'商户入驻“四步曲”',
          name:'1',
          children:[
            {
              title:'一、注册/登录',
              name:'1-1',
              children:[
                {
                  title:'1.注册',
                  name:'1-1-1',
                },
                {
                  title:'2.登录',
                  name:'1-1-2',
                }
              ]
            },
            {
              title:'二、新增售卖商品',
              name:'1-3',
              children:[
                {
                  title:'1.新增商品类型',
                  name:'1-3-1',
                },
                {
                  title:'2.新增商品',
                  name:'1-3-2',
                },
                {
                  title:'3.新增价格模板（选择性）',
                  name:'1-3-3',
                }
              ]
            },
            {
              title:'三、管理设备',
              name:'1-4',
              children:[
                {
                  title:'1.新增分区线路',
                  name:'1-4-1',
                },
                {
                  title:'2.新增点位',
                  name:'1-4-2',
                },
                {
                  title:'3.新增货道商品模板',
                  name:'1-4-3',
                },
                {
                  title:'4.新增利益分配模板',
                  name:'1-4-4',
                },
                {
                  title:'5.设定设备各项信息并“启用”',
                  name:'1-4-5',
                }
              ]
            },
            {
              title:'四、用户分配',
              name:'1-5',
              children:[
                {
                  title:'1.新增角色',
                  name:'1-5-1',
                },
                {
                  title:'2.新增用户',
                  name:'1-5-2',
                }
              ]
            },
          ]
        };  
const five = {
          title:'商户入驻“五步曲”',
          name:'1',
          children:[
            {
              title:'一、注册/登录',
              name:'1-1',
              children:[
                {
                  title:'1.注册',
                  name:'1-1-1',
                },
                {
                  title:'2.登录',
                  name:'1-1-2',
                }
              ]
            },
            {
              title:'二、商户收款码设置',
              name:'1-2',
            },
            {
              title:'三、新增售卖商品',
              name:'1-3',
              children:[
                {
                  title:'1.新增商品类型',
                  name:'1-3-1',
                },
                {
                  title:'2.新增商品',
                  name:'1-3-2',
                },
                {
                  title:'3.新增价格模板（选择性）',
                  name:'1-3-3',
                }
              ]
            },
            {
              title:'四、管理设备',
              name:'1-4',
              children:[
                {
                  title:'1.新增分区线路',
                  name:'1-4-1',
                },
                {
                  title:'2.新增点位',
                  name:'1-4-2',
                },
                {
                  title:'3.新增货道商品模板',
                  name:'1-4-3',
                },
                {
                  title:'4.新增利益分配模板',
                  name:'1-4-4',
                },
                {
                  title:'5.设定设备各项信息并“启用”',
                  name:'1-4-5',
                }
              ]
            },
            {
              title:'五、用户分配',
              name:'1-5',
              children:[
                {
                  title:'1.新增角色',
                  name:'1-5-1',
                },
                {
                  title:'2.新增用户',
                  name:'1-5-2',
                }
              ]
            },
          ]
        };
const nine =  {
              title:'九、平台管理',
              name:'2-9',
              isParent:true,
              children:[
                {
                  title:'1.商户管理',
                  name:'2-9-1',
                  children:[
                    {
                      title:'1.1商户信息管理',
                      name:'2-9-1-1',
                    },
                    {
                      title:'1.2商户收钱码管理',
                      name:'2-9-1-2',
                    }
                  ]
                },
                {
                  title:'2.商品管理',
                  name:'2-9-2',
                },
                {
                  title:'3.设备管理',
                  name:'2-9-3',
                  children:[
                    {
                      title:'3.1设备列表',
                      name:'2-9-3-1',
                    },
                    {
                      title:'3.2设备模板',
                      name:'2-9-3-2',
                    }
                  ]
                },
                {
                  title:'4.交易结算',
                  name:'2-9-4',
                  children:[
                    {
                      title:'4.1交易管理',
                      name:'2-9-4-1',
                    },
                    {
                      title:'4.2结算管理',
                      name:'2-9-4-2',
                    },
                    {
                      title:'4.3结算记录管理',
                      name:'2-9-4-3',
                    }
                  ]
                },
                {
                  title:'5.系统管理',
                  name:'2-9-5',
                },
                {
                  title:'6.会员管理',
                  name:'2-9-6',
                },
                {
                  title:'7.大数据',
                  name:'2-9-7',
                },
              ]
            };
let list = [
        {
          title:'详细教程及功能概览',
          name:'2',
          children:[
            {
              title:'一、首页',
              name:'2-1'
            },
            {
              title:'二、商户（商户信息）',
              name:'2-2',
            },
            {
              title:'三、商品',
              name:'2-3',
              children:[
                {
                  title:'1.商品类型',
                  name:'2-3-1',
                },
                {
                  title:'2.商品中心',
                  name:'2-3-2',
                },
                {
                  title:'3.商品价格模板',
                  name:'2-3-3',
                }
              ]
            },
            {
              title:'四、设备',
              name:'2-4',
              children:[
                {
                  title:'1.设备管理',
                  name:'2-4-1',
                },
                {
                  title:'2.分区线路设置',
                  name:'2-4-2',
                },
                {
                  title:'3.点位管理',
                  name:'2-4-3',
                },
                {
                  title:'4.货道商品模板设置',
                  name:'2-4-4',
                },
                {
                  title:'5.利益分配',
                  name:'2-4-5',
                },
                {
                  title:'6.GIS',
                  name:'2-4-6',
                }
              ]
            },
            {
              title:'五、库存',
              name:'2-5',
              children:[
                {
                  title:'1.库存监控',
                  name:'2-5-1',
                },
                {
                  title:'2.补货记录',
                  name:'2-5-2',
                }
              ]
            },
            {
              title:'六、促销活动（活动列表）',
              name:'2-6',
            },
            {
              title:'七、销售结算',
              name:'2-7',
              children:[
                {
                  title:'1.交易列表',
                  name:'2-7-1',
                },
                {
                  title:'2.结算列表',
                  name:'2-7-2',
                },
                {
                  title:'3.结算记录',
                  name:'2-7-3',
                }
              ]
            },
            {
              title:'八、系统',
              name:'2-8',
              children:[
                {
                  title:'1.用户管理',
                  name:'2-8-1',
                },
                {
                  title:'2.角色管理',
                  name:'2-8-2',
                }
              ]
            },
          ]
        },
        {
          title:'商户APP“云自购”功能概览',
          name:'3',
          children:[
            {
              title:'一、首页',
              name:'3-1',
              children:[
                {
                  title:'1.我的利润',
                  name:'3-1-1',
                },
                {
                  title:'2.库存管理',
                  name:'3-1-2',
                },
                {
                  title:'3.报表查询',
                  name:'3-1-3',
                },
                {
                  title:'4.商品中心',
                  name:'3-1-4',
                },
                {
                  title:'5.维护中心',
                  name:'3-1-5',
                }
              ]
            },
            {
              title:'二、设备管理',
              name:'3-2',
            },
            {
              title:'三、个人中心',
              name:'3-3',
              children:[
                {
                  title:'1.基本信息',
                  name:'3-3-1',
                },
                {
                  title:'2.结算',
                  name:'3-3-2',
                },
                {
                  title:'3.帮助',
                  name:'3-3-3',
                },
                {
                  title:'4.关于',
                  name:'3-3-4',
                }
              ]
            }
          ]
        },
      ];
    if(store.state.user.channelId==1){
      list[0].children.push(nine);
      contentData[0].children.push(nineData);
    }
    if(store.state.user.userVo.type==2&&store.state.user.merchant.receiveTerminal==2){
      list = [five,...list];
      contentData = [fiveData,...contentData]
    }else{
      list = [four,...list];
      contentData = [fourData,...contentData]
    }
export default {
  name:'helpDocument',
  components:{
    centerContent
  },
  data(){
    return{
      contentData:contentData,
      list:list,
    }
  },
  methods:{
    menuChange(value){
      window.location.href=`#${value}`;
      // document.scrollingElement.scrollTop = document.scrollingElement.scrollTop-100;
    }
  }, 
  mounted(){
  }
}
</script>

<style lang="less" scoped>
.helpDocument{
  height: 100%;
  // overflow: auto;
  .ivu-layout{
    height: 100%
  }
  /deep/.ivu-layout-sider{
    background: white
  }
  /deep/.ivu-layout-sider-children{
    width: 300px;
    overflow: auto;
    >ul>li>div.ivu-menu-submenu-title{
      font-weight: 700;
      font-size: 16px
    }
  }
  .centerContent{
    background: white;
    padding:20px 30px
  }
}
</style>